i1=int(input("Enter i coefficient of 1st vector"))
j1=int(input("Enter j coefficient of 1st vector"))
i2=int(input("Enter i coefficient of 2nd vector"))
j2=int(input("Enter j coefficient of 2nd vector"))
print((i1*i2) + (j1*j2),"\n")
